### ISSUE TITLE
Apply the new Eclipse Kanto project license scheme

### ISSUE THREAD

**Issue by konstantina-gramatova** [eclipse-kanto/kanto#114]
The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 and Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).

The following changes must be applied to all project repositories:
* Update all **copyright headers** in the **source files** with the new copyright header:
```
// Copyright (c) {year} Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
```
* Update the **License Header** section of the **CONTRIBUTING.md** file with the new copyright header provided above
* Update the **LICENSE** file to be compliant with the [format recommended by Eclipse](https://www.eclipse.org/projects/handbook/#legaldoc-license):
```
This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
https://www.eclipse.org/legal/epl-2.0, or the Apache Software License
2.0 which is available at https://www.apache.org/licenses/LICENSE-2.0.

... Text of the Eclipse Public License 2.0 ...

... Text of the Apache Software License 2.0 ...

```
* Update the **Declared Project Licenses** section of the **NOTICE.md** file with the new license information, i.e.:
```
This program and the accompanying materials are made available under the terms
of the Eclipse Public License 2.0 which is available at
https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0 which
is available at https://www.apache.org/licenses/LICENSE-2.0.

SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
```
* Update all public web resources to refer to the new license scheme of the project - i.e. [the **project's website**](https://websites.eclipseprojects.io/kanto/) **License** link
* Update the license information in the distribution packages (e.g. Debian, RPM) generated by Go Releaser, i.e.:
```
license: EPL-2.0 or Apache-2.0
```

**Comment by daniel-milchev** [comment]
I'll have a look at this.
