### ISSUE TITLE
Add cloud2edge setup script for integration testing

### ISSUE THREAD

**Issue by nzhechev-bosch** [eclipse-kanto/kanto#126]
Add script to setup cloud2edge resources for integration testing (and clean them up afterwards). 

The script should assume the Hono connection and tenant are already created and provided, and create the required test device with it's policy, auth, etc. Suite connector configuration should be modified to use the test device.

**Comment by dimiter-todorov-georgiev** [comment]
I am taking a look at this issue, please assign it to me
