### ISSUE TITLE
Shutdown order for services must go in opposite direction of starting for the deb package

### ISSUE THREAD

**Issue by dimiter-todorov-georgiev** [eclipse-kanto/kanto#133]
In the files build/prerm and build/postrm, the order of services should be:

system-metrics.service
file-backup.service
software-update.service
file-upload.service
container-management.service
suite-connector.service
local-digital-twins.service
suite-bootstrapping.service

This is the opposite order of us starting the services. We don't start local-digital-twins and suite-bootstrapping by default, but if we do, suite-bootstrapping must be started first, followed by local-digital-twins, so this deactivation order keeps being opposite of that.

**Comment by daniel-milchev** [comment]
I'll have a look at this.
