### ISSUE TITLE
A space is missing after a link

### ISSUE THREAD

**Issue by KatyaGe** [eclipse-kanto/kanto#145]
A space is missing after the first reference to Bosch IoT Device Management here: https://websites.eclipseprojects.io/kanto/docs/getting-started/dmp/
P.S. Congratulations for Kanto M2 :)

**Comment by e-grigorov** [comment]
Thanks for the finding! The documentation will be updated in a few minutes.

> P.S. Congratulations for Kanto M2 :)

Thanks, I hope that you'll find new useful features in this release :)
