### ISSUE TITLE
Investigate the increase of the binary size from Go 1.17 to 1.19 migration

### ISSUE THREAD

**Issue by e-grigorov** [eclipse-kanto/kanto#193]
Here are some numbers for Azure connector:
- Go 1.17.2 - 8.11MB
- Go 1.19.4 - 8.50MB

The size difference has to be investigated and potential optimization has to be integrated.

**Comment by hristobojilov** [comment]
That seems to be related with https://github.com/golang/go/issues/52270.
According to this description some changes in the runtime were introduced related with deferred code execution which cause some code bloat.

**Comment by e-grigorov** [comment]
Nothing to do on our side. Just keep an eye on the linked issue.
