### ISSUE TITLE
Document the extra hosts parameter in the container configuration

### ISSUE THREAD

**Issue by mikehaller** [eclipse-kanto/kanto#197]
The extra_hosts mapping allows to use "host_ip" magic string, but this is not documented anywhere here:
https://websites.eclipseprojects.io/kanto/docs/references/containers/container-config/

**Comment by dimitar-dimitrow** [comment]
The documentation is also updated to reflect the new capability(other bridge container mapping) of extra hosts provided in eclipse-kanto/container-management#122.
