### ISSUE TITLE
Eclipse Kanto M3 release

### ISSUE THREAD

**Issue by ttttodorov** [eclipse-kanto/kanto#221]
The scope of the Eclipse Kanto M3 release is to provide a build with all fixed bugs and applied changes since Eclipse Kanto M2 release, as well as the following important features: 
- https://github.com/eclipse-kanto/container-management/issues/141
- https://github.com/eclipse-kanto/container-management/issues/95
- https://github.com/eclipse-kanto/container-management/issues/114
- AWS IoT Core integration
-- https://github.com/eclipse-kanto/suite-connector/issues/83
-- https://github.com/eclipse-kanto/suite-connector/issues/69
-- https://github.com/eclipse-kanto/suite-connector/issues/78
-- https://github.com/eclipse-kanto/suite-connector/issues/81

**Comment by k-gostev** [comment]
M3 For Eclipse Kanto is now released.
