### ISSUE TITLE
detailed steps required on kanto

### ISSUE THREAD

**Issue by pavithvishnu** [eclipse-kanto/kanto#226]
I'm trying to deploy the kanto on my raspberry pi,  and I would like to use my own hono which is deployed on AKS. 
I have changed the parameters in the config file to suite connector. And restarted the service. But whenever I check logs on suite connector it is showing that it is connected with tcp://localhost:1883. Even Though I have changed the connection in the config file.
Also commands which I'm send from the hono is also not reaching to kanto.
Similarity need docs for how to configure the other services.

**Comment by k-gostev** [comment]
Hi @pavithvishnu, could you provide the suite connector config file?

**Comment by pavithvishnu** [comment]
{
    "provisioningFile":"/etc/suite-connector/provisioning.json",
    "logFile":"/var/log/suite-connector/suite-connector.log",
    "address":"mqtt://20.219.231.232:1883",
    "tenantId":"kanto-demo",
    "deviceId":"kanto:device1",
    "authId":"kanto_device1",
    "password":"kanto1234"
}

**Comment by k-gostev** [comment]
Hi, sorry for the late response, the config looks good, ` tcp://localhost:1883` is the default address for the local `mqtt` communication, so I don't see anything suspicious there. As I don't have more information (like logs) I can only advise you to double check the remote configuration, make sure that the local mqtt broker is running and check for network related issues.
For the documentation we already have a [getting started guide](https://eclipse.dev/kanto/docs/getting-started/hono/) that walks you trough the steps of connecting and starting managing devices via Eclipse Hono.
