### ISSUE TITLE
AWS Connector Feature Request - AWS Connectivity option with Device Shadows

### ISSUE THREAD

**Issue by stlevkov-bosch** [eclipse-kanto/kanto#254]
Dear Kanto team,

I am currently working on a project, which requires AWS connectivity from edge devices. We are thinking of using Kanto for PoCs, but we are not able to find an option to connect our applications with the AWS IoT Core using Kanto deployed on the edge device.
If its possible, would be really nice to have **AWS Connector** - very similar to the Azure Connector. The following requirements can be used as a starting point, which we believe can be beneficial to others as well:

- AWS Thing Connectivity with certificate using MQTT
- Thing/Shadow **reported** state update - using Device Shadows (I would like to address here, that there is a limitation of the JSON documents in the device shadows, which we believe will reflect on the ditto messages payload, but this is expected)
- If possible, to have each Ditto feature (path) separated in different Shadow
- Would be great if it has _connection-fail auto-handling mechanism_ to keep the device always connected in case of network issues.

This definition of AWS Connector should be enough to have a stable, easy to use and robust connectivity option with AWS with the Kanto stack.

Please, let me know if you need additional details regarding this feature request.

Kindly thank you in advance for the provided support.

**Comment by k-gostev** [comment]
Thank you for this proposal, IMO it would be indeed beneficial to AWS IoT Core connectivity out of the box in Kanto.

**Comment by k-gostev** [comment]
The AWS Connector is now merged. We will continue with the related discussion in its repository.
