### ISSUE TITLE
Update Container Manager reference guide

### ISSUE THREAD

**Issue by dimitar-dimitrow** [eclipse-kanto/kanto#265]
As the Container Manager local communication properties were moved outside of the things service - [container-management#169](https://github.com/eclipse-kanto/container-management/issues/169), the Container Manager reference guide should be updated. The old local connection properties should be marked as deprecated and the new one should be added.

**Comment by stoyan-zoubev** [comment]
I can take this. @dimitar-dimitrow please assign it to me.
