### ISSUE TITLE
Example application to connect kuksa and kanto

### ISSUE THREAD

**Issue by mage8091** [eclipse-kanto/kanto#322]
Dear Kanto Team,

I am working on an internal demo within my company using Kanto.  I wanted to use Kuksa databroker to get the vehicle data and need to transfer the data to AWS cloud. Would it be possible to create an example application that would demonstrate connection between kuksa and kanto? 

Regards,
Marydas George

**Comment by karthik2143** [comment]
Hello,

In the process of creating a demonstration app for KUKSA and KANTO interoperability.

**Comment by k-gostev** [comment]
hi @mage8091, an example application is added. Please check https://github.com/eclipse-kanto/example-applications/tree/main/kuksa
If you have more questions or you need further support, please reopen this issue.
