### ISSUE TITLE
Missing footer Last modified in the web site with the new hugo modules

### ISSUE THREAD

**Issue by antonia-avramova** [eclipse-kanto/kanto#323]
In the new web site with hugo modules there are missing "Last modified ..." footer.
old version:
![image](https://github.com/eclipse-kanto/kanto/assets/94553167/f9de0182-df26-4686-83b5-0fd269fbafbb)

new version:
![image](https://github.com/eclipse-kanto/kanto/assets/94553167/9de23e6b-8127-44b6-aa0d-e7b8c791aff2)

**Comment by k-gostev** [comment]
Tanks @antonia-avramova, nice catch!
