### ISSUE TITLE
Provide Reference guide for the Kanto Azure Connector

### ISSUE THREAD

**Issue by e-grigorov** [eclipse-kanto/kanto#50]
* Provide the information relevant to available configurations per a Azure Connector instance
* Add an example of how to use this configuration
* This reference guide must be included in Eclipse Kanto Documentation
* This reference guide should be placed in a new group together with Suite Connector and Suite Bootstrapping
* The order should be: Suite Connector, Suite Bootstrapping, Azure Connector

**Comment by k-gostev** [comment]
This is already implemented
