### ISSUE TITLE
Code snippets in Eclipse Kanto public documentation are not displayed properly

### ISSUE THREAD

**Issue by ognian-baruh** [eclipse-kanto/kanto#57]
The code snippets in the Getting Started guides in the [Eclipse Kanto public documentation](https://websites.eclipseprojects.io/kanto/docs/) are not formatted as code and therefore cannot be copied via the "Copy" button in the top right corner.

The affected pages in the documentation are:

- [Install Eclipse Kanto](https://websites.eclipseprojects.io/kanto/docs/getting-started/install/)
- [Explore via Eclipse Hono](https://websites.eclipseprojects.io/kanto/docs/getting-started/hono/)

**Comment by daniel-milchev** [comment]
I'll have a look at this.

**Comment by daniel-milchev** [comment]
The problem with these code snippets is related to Hugo version 101. "prism.js", "prism.css" and "tabpane-persist,js" are not found in the "scripts.html" file because the baseURL is not prepend to the relURL.

This issue is related with gohugoio/hugo#9994.

**Comment by chalin** [comment]
Hi all. FYI, I've merged a fix: https://github.com/google/docsy/pull/1127. Could you try it out and offer some feedback?

It seems to work when I build your site (still using Hugo v0.101.0):

> <img width="933" alt="image" src="https://user-images.githubusercontent.com/4140793/181295898-2b9738b5-19c2-4f04-b616-d0eaf7c3fe09.png">

**Comment by daniel-milchev** [comment]
The problem with the code snippets has been resolved google/docsy#1127

**Comment by konstantina-gramatova** [comment]
The issue will be resolved when Kanto's website is migrated to Hugo modules enabling to update it to the latest Docsy released version that includes this fix (when available) (see #110). Also the downgrade of Hugo workaround (#72) will be discarded along this migration.

**Comment by k-gostev** [comment]
Kanto's website is now migrated to Hugo Modules and this issue is resolved
