### ISSUE TITLE
Revert Hugo version

### ISSUE THREAD

**Issue by daniel-milchev** [eclipse-kanto/kanto#72]
Due to [the bug](https://github.com/eclipse-kanto/kanto/issues/57#issuecomment-1196509622) in the newest Hugo version affecting relURL's, the version has to be reverted until the bug is fixed.

**Comment by chalin** [comment]
You might not need to revert, see https://github.com/eclipse-kanto/kanto/issues/57#issuecomment-1196963764.

**Comment by daniel-milchev** [comment]
Based on the google/docsy#1127 commit, there will be no need to revert the Hugo version.
