### ISSUE TITLE
Fix website UI formatting

### ISSUE THREAD

**Issue by konstantina-gramatova** [eclipse-kanto/kanto#83]
After the latest website tooling and dependencies migration:
* Hugo 0.8x.x -> 0.100.2
* Docsy [Snapshot@9f55cf348](https://github.com/google/docsy/tree/9f55cf34808d720bcfff9398c9f9bb7fd8fce4ec) -> [v0.3.0](https://github.com/google/docsy/releases/tag/v0.3.0) 

the formatting of some sections has been changed causing e.g.:
* improper unaligned visualization of some of the components
* font size changes

E.g:
Previous website version:
![image](https://user-images.githubusercontent.com/58775347/184069474-03e2e591-ee7e-4572-b2a3-65a7bb19889b.png)

Current website version:
![image](https://user-images.githubusercontent.com/58775347/184069547-53cdef71-8474-4baf-b887-9d9a9b28ea17.png)

The newly built website must be examined for further issues caused by the tooling/dependencies migration alongside fixing the listed already found ones above.

**Comment by daniel-milchev** [comment]
I'll have a look at this.

**Comment by daniel-milchev** [comment]
Tried to change hugo and docsy versions but it didn't seem to work. I also checked if some of the css files were wrong but they seem to be ok. I need to further look into it.
