### ISSUE TITLE
Provide Reference guide for the Kanto File Backup

### ISSUE THREAD

**Issue by e-grigorov** [eclipse-kanto/kanto#89]
* Provide the information relevant to available configurations per a Kanto File Backup instance
* Add an example of how to use this configuration
* This reference guide must be included in Eclipse Kanto Documentation
* In respect to the order, this document should be placed right after the file upload

**Comment by velitchko-valkov** [comment]
I will write this documentation.

**Comment by konstantina-gramatova** [comment]
@velitchko-valkov The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).

This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances :blush: 

Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!
