### ISSUE TITLE
Ensure graceful exit of the quickstart Python script and the How-to guide Python scripts

### ISSUE THREAD

**Issue by ognian-baruh** [eclipse-kanto/kanto#98]
Currently, the command response handlers of the Python scripts quit the process upon receival of a message, preventing themselves from gracefully exiting the `on_message` callback method. As a result the connection to the Eclipse Hono Sandbox is lost, preventing secondary execution of the scripts before reconnection.

The issue is raised to the Eclipse Hono project in [this issue](https://github.com/eclipse-hono/hono/issues/3393).

To temporary workaround the described issue the exit of the scripts could be done asynchronously - i.e. by using the on_connection_closed callback. This will ensure that the message processing will not be interrupted in any way so that the connection stays intact.

The affected Python scripts are:
- The Python script used in the Explore via Eclipse Hono guide - [hono_command.py](https://github.com/eclipse-kanto/kanto/blob/main/quickstart/hono_commands.py)
- The Python script used in the Software Update How-to guide [hono_command_su.py](https://github.com/eclipse-kanto/kanto/blob/main/quickstart/hono_commands_su.py)
- The Python script used in the File Upload How-to guide [hono_command_fu.py](https://github.com/eclipse-kanto/kanto/blob/main/quickstart/hono_commands_fu.py)

**Comment by daniel-milchev** [comment]
I'll have a look at this.

**Comment by konstantina-gramatova** [comment]
The behavior in the AMQP handlers for Hono events is secured too regardless the described issue is not present there (as explained [here](https://github.com/eclipse-hono/hono/issues/3393#issuecomment-1238993968)). The workaround is added there as well for completeness and code consistency.
